version: '3'

networks:
  restapi_network:
    driver: bridge

services:
  app:
    container_name: nodejs
    build: .
    ports:
    - ${PORT}:${PORT}
    depends_on:
      - db
    working_dir: /usr/app
    env_file:
      - ./.env
    volumes:
      - ./logs:/usr/app/logs
      - ./src:/usr/app/src
    networks:
      - restapi_network
    restart: unless-stopped

  db:
    container_name: ${DB_HOST}
    build: ./database/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${DB_DATA}:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - restapi_network
    restart: unless-stopped
