version: '3'

networks:
  restapi_network:
    driver: bridge

services:
  node:
    build: .
    image: evanre/rss-docker-basics-node
    ports:
    - ${PORT}:${PORT}
    depends_on:
      - postgres
    working_dir: /usr/app
    volumes:
      - ./logs:/usr/app/logs
      - ./src:/usr/app/src
    environment:
      - PORT=${PORT}
    networks:
      - restapi_network
    restart: unless-stopped

  postgres:
    build: ./database/
    image: evanre/rss-docker-basics-postgres
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    networks:
      - restapi_network
    restart: unless-stopped
