version: '3'

networks:
  restapi_network:
    driver: bridge

services:
#  app:
#    container_name: nodejs
#    build: .
#    ports:
#    - ${PORT}:${PORT}
#    depends_on:
#      - db
#    working_dir: /usr/app
#    env_file:
#      - ./.env
#    volumes:
#      - ./logs:/usr/app/logs
#      - ./src:/usr/app/src
#      - ./package.json:/usr/app/package.json
#    networks:
#      - restapi_network
#    restart: unless-stopped

  db:
    image: postgres:alpine
    container_name: ${POSTGRES_HOST}
    env_file:
      - ./.env
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - restapi_network
    restart: unless-stopped
